@startuml
class Companhia{

}

class Passagem{
    - Valor : double
    - CustoOperacional : double
}

class Economica{
}

class Executiva{
}

class PrimeiraClasse{
}


Passagem <-- Economica
Passagem <-- Executiva
Passagem <-- PrimeiraClasse
@enduml